repos:
  - repo: local
    hooks:
      - id: ktlint
        name: ktlint-check-and-format
        entry: bash -c './gradlew ktlintCheck || ./gradlew ktlintFormat'
        language: system
        types: [kotlin]
