micronaut:
  auth:
    issuers:
      labid:
        - https://labid.lab.dapla-external.ssb.no
      keycloak:
        - https://auth.ssb.no/realms/ssb
logger:
  config: logback-kubernetes.xml

mongodb:
  uri: ${MONGODB_CONNECTION_STRING:}
