micronaut:
  auth:
    issuers:
      labid:
        - https://labid.lab.dapla-test-external.ssb.no
      keycloak:
        - https://auth.test.ssb.no/realms/ssb
  http:
    services:
      keycloak:
        url: https://auth.test.ssb.no/
        clientId: vardef-to-dapla-team-api-m2m
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
      dapla-api:
        url: https://dapla-ctrl.intern.ssb.no
  metrics:
    custom:
      # Used for exporting custom business metrics
      update-frequency: 1m
      initial-delay: 0s
logger:
  config: logback-kubernetes.xml

mongodb:
  uri: ${MONGODB_CONNECTION_STRING:}
