micronaut:
  security:
    token:
      jwt:
        claims:
          values:
            allowed-audiences:
              - dapla-cli
              - onyxia-api
              - vardef
  http:
    services:
      dapla-team-api:
        url: http://dapla-team-api.dapla-platform
      keycloak:
        url: https://auth.test.ssb.no/
        clientId: vardef-to-dapla-team-api-m2m
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  metrics:
    custom:
      # Used for exporting custom business metrics
      update-frequency: 1m
      initial-delay: 0s
logger:
  config: logback-kubernetes.xml

mongodb:
  uri: ${MONGODB_CONNECTION_STRING:}
