micronaut:
  auth:
    issuers:
      labid:
        - https://labid.lab.dapla-external.ssb.no
      keycloak:
        - https://auth.ssb.no/realms/ssb
  http:
    services:
      keycloak:
        url: https://auth.ssb.no/
        clientId: vardef-to-dapla-team-api-m2m
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
      dapla-api:
        url: https://dapla-ctrl.intern.ssb.no
logger:
  config: logback-kubernetes.xml

mongodb:
  uri: ${MONGODB_CONNECTION_STRING:}
