
name: Run tests

on:
  push:
    paths:
      - src
      - gradle/libs.versions.toml
      - build.gradle.kts
      - .github/workflows/run-tests.yml

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: v28.0.0
          set-host: 'true'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and test project
        run: >
          ./gradlew
          test
          jacocoTestReport
          --daemon --parallel --build-cache

  check-format-and-code-quality:
    name: Check format and code quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Check format
        run: >
          ./gradlew
          ktlintCheck
          --daemon --parallel --build-cache

      - name: SonarQube Cloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # No need to run SonarCloud analysis if dependabot update or token not defined
        if: env.SONAR_TOKEN != '' && (github.actor != 'dependabot[bot]')
        uses: SonarSource/sonarqube-scan-action@v7.0.0
